---
- name: Testing andrewrothstein.argo
  hosts: all
  tasks:
    - name: Installing andrewrothstein.argo
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'argo version'
      ansible.builtin.command: /usr/local/bin/argo version
      changed_when: false
      register: argo_test_output
    - name: Output from 'argo version'
      ansible.builtin.debug:
        msg: '{{ argo_test_output.stdout }}'
